backend:
  name: git-gateway
  branch: main
media_folder: "/public/images/"
public_folder: "images/"
collections:
  - name: "articles"
    label: "Artikel"
    folder: "src/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "text" }
      - { label: "Bild", name: "image", widget: "image", required: false, default: "/images/placeholder.png" }
      - { label: "Bild Text", name: "image_text", widget: "string", required: false, default: "placeholder" }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["articles"] }
  - name: "category"
    label: "Kategorie"
    folder: "src/category"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["category"] }
      - label: Gallery
        name: galleryImages
        widget: list
        fields:
          - { label: Image, name: image, widget: image }
          - { label: Link, name: link, widget: string }
          - { label: Titel, name: link_text, widget: string }
  - name: "other"
    label: "Andere"
    folder: "src/other"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "text", required: false }
      - { label: "Bild", name: "image", widget: "image", required: false, default: "/images/placeholder.png" }
      - { label: "Bild Text", name: "image_text", widget: "string", required: false, default: "placeholder" }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "news"
    label: "News"
    folder: "src/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "text", required: true }
      - { label: "Bild", name: "image", widget: "image", required: false, default: "/images/placeholder.png" }
      - { label: "Bild Text", name: "image_text", widget: "string", required: false, default: "placeholder" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "sponsoren"
    label: "Sponsoren"
    folder: "src/sponsor"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string", required: true }
      - { label: "Adresse", name: "adresse_1", widget: "string", required: true }
      - { label: "PLZ Ort", name: "adresse_2", widget: "string", required: true }
      - { label: "Bild", name: "image", widget: "image", required: false }
      - { label: "Bild Text", name: "image_text", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: "sponsor" }
#  - label: FAQS
#    name: faqs
#    create: true
#    folder: "src/other/faq"
#    widget: list
#    fields:
#      - label: FAQ
#        name: faq
#        widget: list
#        fields:
#          - { label: Question, name: question, widget: string, default: "Question" }
#          - { label: Answer, name: answer, widget: string, default: "Answer" }
